version: '3.8'
services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      # - "/home/panda/jenkins:/var/jenkins_home"
      - /home/panda/pandas-infrastructure/jenkins_controller/casc.yaml:/usr/share/jenkins/ref/casc.yaml